# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'azureDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for azureDemo
  pod 'MobileCenter/Analytics', '~> 0.11.2'
  pod 'RNMobileCenterShared', '~> 0.8.1'

  

  target 'azureDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'azureDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for azureDemo-tvOS

  target 'azureDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
